%% ModelFactory
% Licensed under the zlib license. See LICENSE for more details.
%

function mainFig = ui_setupHumanOptions(mainFig)

bck_HumanPanel = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Horizontalalignment','left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.01,0.05,0.2,.88]);

txt_EnvOptions = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Loaded Environment',...
    'Tag','txt_EnvOptions',...
    'FontWeight','bold',...
    'FontSize', 12,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.01,0.9,0.2,.02]);

txt_HumanDescription = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Human Description',...
    'Tag','txt_EnvOptions',...
    'Horizontalalignment','left',...
    'FontSize', 12,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.02,0.85,0.15,.02]);

popup_humanModelDescription = uicontrol('Style', 'pushbutton','String','Reload',...
    'Parent', mainFig,...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Tag','popup_humanModelDescription',...
    'Position', [0.16,0.85,0.04,0.02], ...
    'Enable', 'off',...
    'Callback',  @ui_readHumanModelDescriptionFile);
 
txt_humanModelFileName = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Tag','txt_humanModelFileName',...
    'String', mainFig.UserData.humanModelDescription,...
    'Horizontalalignment','left',...
    'FontSize', 8,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.03,0.83,0.15,.02]);

txt_Scaling = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Scaling Algorithm',...
    'Horizontalalignment','left',...
    'Tag','txt_EnvOptions',...
    'FontSize', 12,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.02,0.81,0.15,.02]);

popup_menuScaling = uicontrol('Style', 'popup',...
    'Parent', mainFig,...
    'String', mainFig.UserData.scalingAlgorithmOptions,...
    'Value', 1,...
    'Tag', 'popup_menuScaling',...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.03,0.79,0.15,0.02], ...
    'Callback', @ui_setScalingAlgorithm);
 
txt_Anthro = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Human Anthropometry',...
    'Tag', 'txt_EnvOptions',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Horizontalalignment','left',...
    'Enable', 'off',...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Position', [0.02,0.75,0.15,.02]);

text_personAge = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Age (years)',...
    'Tag', 'txt_EnvOptions',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.02 0.72 0.05 0.02]);

input_personAge = uicontrol('Style', 'edit',...
    'Tag', 'input_personAge',...
    'String', '',...
    'FontSize', 10,...
    'Enable', 'off',...
    'Units', 'normalized',...
    'Position', [0.07 0.72 0.02 0.02]);

text_personHeight = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Height (m)',...
    'Tag', 'txt_EnvOptions',...
    'Enable', 'off',...
    'FontSize', 10,...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.11 0.72 0.05 0.02]);

input_personHeight = uicontrol('Style', 'edit',...
    'Tag', 'input_personHeight',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.17 0.72 0.02 0.02]);

text_personWeight = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Weight (kg)',...
    'Tag', 'txt_EnvOptions',...
    'Enable', 'off',...
    'FontSize', 10,...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.02 0.69 0.05 0.02]);

input_personWeight = uicontrol('Style', 'edit',...
    'Tag', 'input_personWeight',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.07 0.69 0.02 0.02]);

text_personPelvisWidth = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Pelvis Width (m)',...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.11 0.69 0.06 0.02]);

input_personPelvisWidth = uicontrol('Style', 'edit',...
    'Tag', 'input_personPelvisWidth',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.17 0.69 0.02 0.02]);
 
text_personHipCenterWidth = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Hip Center Width (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.02 0.65 0.05 0.03]);

input_personHipCenterWidth = uicontrol('Style', 'edit',...
    'Tag', 'input_personHipCenterWidth',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.07 0.65 0.02 0.02]);
 
text_personShouderCenterWidth = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Shoulder Width (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.11 0.65 0.05 0.03]);

input_personShoulderCenterWidth = uicontrol('Style', 'edit',...
    'Tag', 'input_personShoulderCenterWidth',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.17 0.65 0.02 0.02]);

text_personFootWidth = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Foot Width (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.11 0.61 0.05 0.03]);

input_personFootWidth = uicontrol('Style', 'edit',...
    'Tag', 'input_personFootWidth',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.17 0.61 0.02 0.02]);
 
text_personHeelAnkleXOffset = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Heel-Ankle X Offset (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.02 0.60 0.05 0.04]);

input_personHeelAnkleXOffset = uicontrol('Style', 'edit',...
    'Tag', 'input_personHeelAnkleXOffset',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.07 0.61 0.02 0.02]);
 
text_personHeelAnkleZOffset = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Heel-Ankle Z Offset (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.02 0.56 0.05 0.04]);

input_personHeelAnkleZOffset = uicontrol('Style', 'edit',...
    'Tag', 'input_personHeelAnkleZOffset',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.07 0.57 0.02 0.02]);
 
text_personShoulderNeckZOffset = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Shoulder- Neck Z Offset (m)',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.11 0.56 0.06 0.04]);

input_personShoulderNeckZOffset = uicontrol('Style', 'edit',...
    'Tag', 'input_personShoulderNeckZOffset',...
    'String', '',...
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.17 0.57 0.02 0.02]);

text_personGender = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Gender',...
    'HorizontalAlignment', 'left',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Tag', 'txt_EnvOptions',...    
    'Enable', 'off',...
    'FontSize', 10,...
    'Units', 'normalized',...
    'Position', [0.02 0.53 0.15 0.02]);

checkBox_genderMale = uicontrol('Style', 'checkbox',...
    'Tag', 'checkBox_genderMale',...
    'Parent', mainFig,...
    'HorizontalAlignment', 'left',...
    'String', 'Male',...
    'FontSize', 10,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Value', 1, ...
    'Units', 'normalized',...
    'Position', [0.07 0.53 0.04 0.02],...
    'Callback', @ui_updateMaleGender);

checkBox_genderFemale = uicontrol('Style', 'checkbox',...
    'Tag', 'checkBox_genderFemale',...
    'Parent', mainFig,...
    'HorizontalAlignment', 'left',...
    'String', 'Female',...
    'FontSize', 10,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Value', 0, ...
    'Units', 'normalized',...
    'Position', [0.11 0.53 0.04 0.02],...
    'Callback', @ui_updateFemaleGender);
 
checkBox_addMarkers = uicontrol('Style', 'checkbox',...
    'Tag', 'checkBox_addMarkers',...
    'Parent', mainFig,...
    'HorizontalAlignment', 'left',...
    'FontSize', 10,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'String', 'Add Markers to Model',...
    'Value', 0, ...
    'Units', 'normalized',...
    'Position', [0.02 0.50 0.16 0.02]);

txt_meshOption = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Meshes Type',...
    'Horizontalalignment','left',...
    'Tag','txt_EnvOptions',...
    'FontSize', 10,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.02,0.47,0.15,.02]);

popup_meshTypeOptions = uicontrol('Style', 'popup',...
    'Parent', mainFig,...
    'String', mainFig.UserData.meshTypeOptions,...
    'Value', 1,...
    'Tag', 'popup_meshTypeOptions',...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.1,0.47,0.06,0.02], ...
    'Callback', @ui_setScalingAlgorithm);
