%% ModelFactory
% Licensed under the zlib license. See LICENSE for more details.
%
function mainFig = ui_setupExportOptions(mainFig)

bck_exportPanels = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Horizontalalignment','left',...
    'Backgroundcolor',[0.6 0.6 0.6],...
    'Units', 'normalized',...
    'Position', [0.78,0.35,0.2,.2]);

popup_SaveLua = uicontrol('Style', 'pushbutton',...
    'String','Export Lua Model(s)',...
    'Tag', 'popup_saveLua',...
    'Parent', mainFig,...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.8,0.5,0.15,0.03], ...
    'Callback',  @ui_exportLuaFile);

popup_SaveCombinedLua = uicontrol('Style', 'pushbutton',...
    'Tag', 'popup_saveCombinedLua',...
    'Parent', mainFig,...
    'String',{'Export Combined Lua Model'},...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.8,0.4,0.15,0.03], ...
    'Callback',  @ui_exportCombinedLuaFile);