%% ModelFactory
% Licensed under the zlib license. See LICENSE for more details.
%

function mainFig = ui_setupObjectOptions(mainFig)

txt_demark = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', '----------------------------------',...
    'Horizontalalignment','center',...
    'FontSize', 10,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.03,0.43,0.15,.02]);

txt_ObjectList = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Object List',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Horizontalalignment','left',...
    'Tag','txt_EnvObjectOptions',...
    'Enable','off',...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Position', [0.02,0.40,0.1,.03]);
 
popup_menuObjectList = uicontrol('Style', 'popup',...
    'Parent', mainFig,...
    'String', mainFig.UserData.objectList,...
    'Value', 1,...
    'Tag', 'popup_menuObjectList',...
    'Units', 'normalized',...
    'Enable','on',...
    'Position', [0.1,0.40,0.1,0.03], ...
    'Callback', @ui_setCurrentObject);

txt_ObjectDescription = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Object Model Description',...
    'Tag','txt_EnvObjectOptions',...
    'Horizontalalignment','left',...
    'FontSize', 12,...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Enable', 'off',...
    'Position', [0.02,0.36,0.15,.02]);

txt_objectModelFileName = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Tag','txt_objectModelFileName',...
    'String', '',...
    'Horizontalalignment','left',...
    'FontSize', 8,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.03,0.34,0.15,.02]);
  
txt_ObjectSetup = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Object Setup',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Horizontalalignment','left',...
    'Tag','txt_EnvObjectOptions',...
    'Enable','off',...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Position', [0.02,0.31,0.1,.02]);

txt_objectSetupChoice = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Tag','txt_objectSetupChoice',...
    'String', '',...
    'Horizontalalignment','left',...
    'FontSize', 8,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.03,0.29,0.15,.02]);

txt_ObjectMass = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'String', 'Object Mass Properties',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Horizontalalignment','left',...
    'Tag','txt_EnvObjectOptions',...
    'Enable','off',...
    'FontSize', 12,...
    'Units', 'normalized',...
    'Position', [0.02,0.26,0.1,.02]);

txt_objectMassFile = uicontrol('Style', 'text',...
    'Parent', mainFig,...
    'Tag','txt_objectMassFile',...
    'String', '',...
    'Horizontalalignment','left',...
    'FontSize', 8,...
    'Enable', 'off',...
    'Backgroundcolor',[0.7 0.7 0.7],...
    'Units', 'normalized',...
    'Position', [0.03,0.24,0.15,.02]);